[package]
name = "skuld"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
strip = "symbols"
debug = 0

[dependencies]
chrono = "0.4"
